<?php
session_start();
include("config.php");

if (
    !isset($_SESSION['user_id']) ||
    !in_array($_SESSION['role'], ['admin', 'hr'])
) {
    header("Location: login.php");
    exit();
}

$role = $_SESSION['role'];

if ($role === 'hr') {
    $filename = "hr_report_" . date("Y-m-d_H-i-s") . ".csv";
} else {
    $filename = "admin_users_report_" . date("Y-m-d_H-i-s") . ".csv";
}

header("Content-Type: text/csv; charset=UTF-8");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");

$output = fopen("php://output", "w");

fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

fputcsv($output, ["OneFlow Report"]);
fputcsv($output, ["Generated By Role", ucfirst($role)]);
fputcsv($output, ["Generated At", date("Y-m-d H:i:s")]);
fputcsv($output, []);

fputcsv($output, ["Users"]);
fputcsv($output, ["ID", "Full Name", "Username", "Email", "Role", "Account Status", "Salary", "Birth Date"]);

$query = "
    SELECT id, full_name, username, email, role, account_status, salary, birth_date
    FROM users
    ORDER BY id DESC
";

$result = mysqli_query($conn, $query);

if ($result) {
    while ($row = mysqli_fetch_assoc($result)) {
        fputcsv($output, [
            $row['id'],
            $row['full_name'],
            $row['username'],
            $row['email'],
            ucfirst($row['role']),
            $row['account_status'],
            $row['salary'],
            $row['birth_date']
        ]);
    }
}

fputcsv($output, []);
fputcsv($output, ["Leave Requests"]);
fputcsv($output, ["ID", "Employee", "Leave Type", "Start Date", "End Date", "Status", "Created At"]);

$leaveQuery = "
    SELECT id, employee_name, leave_type, start_date, end_date, status, created_at
    FROM leave_requests
    ORDER BY id DESC
";

$leaveResult = mysqli_query($conn, $leaveQuery);

if ($leaveResult) {
    while ($leave = mysqli_fetch_assoc($leaveResult)) {
        fputcsv($output, [
            $leave['id'],
            $leave['employee_name'],
            $leave['leave_type'],
            $leave['start_date'],
            $leave['end_date'],
            $leave['status'],
            $leave['created_at']
        ]);
    }
}

fclose($output);
exit();
?>